// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bvtzwfkdpklooujmwfbu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ2dHp3ZmtkcGtsb291am13ZmJ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU2MDUyMDUsImV4cCI6MjA1MTE4MTIwNX0.faqR0Fns2afsIUPzFR6W5kV-s-SqnrQYTqYXi0MaIlw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);